### ISSUE TITLE
Detect when the open hex file has changed, and offer to reflash

### ISSUE THREAD

**Issue by ItsHarper** [qmk/qmk_flasher#25]
Inspired by Notepad++

**Comment by ItsHarper** [comment]
A bit of research suggests that [this npm module](https://github.com/paulmillr/chokidar) is the way to do it.

**Comment by skullydazed** [comment]
What form do you envision the offer taking?

**Comment by ItsHarper** [comment]
What do you think of this? The button changes depending on if a device is detected.
![image](https://cloud.githubusercontent.com/assets/10224994/21363569/1fd56efa-c6bb-11e6-9182-faeb2a3a6f14.png)

**Comment by ItsHarper** [comment]
The OK button should say cancel, or the second sentence should be removed from the prompt.

**Comment by ItsHarper** [comment]
I think it would also be good if the window came to the foreground when this happens.

**Comment by skullydazed** [comment]
The wording is good, and the behavior seems good. I think on OS X it should be a drawer that slides out from under the window, and I think you get this for free if you're using the JS window.confirm. I'm not sure what node alternatives there are that would have a similar effect, but that'd be worth tracking down.

**Comment by ItsHarper** [comment]
Good point about macOS. Unfortunately, a quick Google search says that you can't customize the button text if you use the built in js function. I'll have to see if there's a library or something that calls the Mac API directly.

**Comment by skullydazed** [comment]
Re: coming to the foreground, I could see this being disliked by a vocal minority, liked by a minority, and being indifferent otherwise. Perhaps we need to offer it as a preference if we implement it?

**Comment by ItsHarper** [comment]
What do you get when you run this code in the developer tools console on Mac? (Cmd+Shift+i to open it I think) Does it do the pop-down thing?

`dialog.showMessageBox({
type: "info",
buttons: [],
message: "Hello world",
});`

**Comment by ItsHarper** [comment]
Nevermind, this is from the Electron docs

> **Sheets**
>On macOS, dialogs are presented as sheets attached to a window if you provide a BrowserWindow reference in the browserWindow parameter, or modals if no window is provided.
>You can call BrowserWindow.getCurrentWindow().setSheetOffset(offset) to change the offset from the window frame where sheets are attached.

**Comment by ItsHarper** [comment]
The problem with electron's dialog object though, is that you can't change the button text after bringing up the prompt. [The library used in the screenshot, Bootbox,](https://github.com/makeusabrew/bootbox) makes use of Boostrap modals, and you can change the button text after the dialog is displayed.

**Comment by skullydazed** [comment]
Do we need to change the text after bringing up the prompt, or can we live with not being able to change the button if they press reset after the dialog is shown?

Thinking about other directions that may sidestep this issue, what if we wrote to the status window instead? A message there could prompt the user to flash. Alternatively, we could use an overlay to draw an arrow pointing at the flash button with a message saying, "the hex file has changed, click that to flash"

**Comment by ItsHarper** [comment]
If it's a choice between buttons that accurately reflect the current state and feel correct within the context of the app, or buttons that show stale data but fit in a bit more nicely with the OS, I'm going to choose the former. My opinion is that stale data can hurt usability far more than an incorrectly-styled alert box. 

With the main use case I'm thinking of here, bring-to-front is a vital component. If we're going to have bring-to-front, it should be _very_ obvious why that's happening. 

Writing to the status window would be too subtle, and overlays like that are usually used in tutorials. I feel like it would be hard to make the overlay option feel "right", especially for explaining why a window just popped into the foreground. I'm open to that option if you can provide a convincing demo though.

Alerts are really the right choice to say "ignore everything else and look here". I wish we could easily pull up the native Mac dialog in a way that lets us update the buttons, but it's not like using the bootbox dialog will confuse any Mac users, right? 

As a side note, it should technically be possible to write a node addon that will let you call the native Mac API, which, as I confirmed through a quick test in a Swift playground, will let you create sheets and then modify the button text. That's going to probably be a bit of a hassle though.
