### ISSUE TITLE
qmk flasher no longer working after using tkg

### ISSUE THREAD

**Issue by backstabbd88** [qmk/qmk_flasher#38]
i have a xd60 pcb and windows 10.

I was able to use qmk firmware flasher originally, and successfully flashed qmk firmware.

Tried to switch to tmk just to try it out because backlight controls on xd60 doesnt work with qmk. (something to do with pwm pin b5 b6 & b7).

I wanted to go back to qmk firmware but i can no longer flash with it. The app cant seem to detect my keyboard when i put it to dfu bootloader mode. the flash button stays red.

![qmk](https://cloud.githubusercontent.com/assets/24477221/22151097/79836c54-df57-11e6-9866-0873e6a850c6.png)

 I'm pretty sure that i put my keyboard in bootloader mode, since i can flash tkg with no problem.

**Comment by skullydazed** [comment]
After putting your keyboard into bootloader mode can you find it in Device Manager? That will help us determine what might be going on.

**Comment by backstabbd88** [comment]
thank you.
yes, atmega32u4 shows up. i have tried unstalling/reinstall drivers. reinstalling qmk flasher. changing usb port. still can't find what is causing the issue.

![qmk](https://cloud.githubusercontent.com/assets/24477221/22151235/328cb6ec-df58-11e6-8452-86cf3b09ee8f.png)

**Comment by skullydazed** [comment]
Huh, that's really unusual. Let me dig into it a bit more and see if I can't figure something out.

**Comment by backstabbd88** [comment]
thank you so much skullydazed, i'll also try to use a different PC tomorrow.

**Comment by ItsHarper** [comment]
OK, I've got something to go on.

Your flashable keyboard is showing up in device manager, but I think not how it should be (unless it's something different for your keyboard). In dfu mode, my Planck shows up not under USB devices, but under "Atmel USB Devices", and it's named "ATmega32U4".

@backstabbd88 Can you show me the driver tab of your device window?

**Comment by ItsHarper** [comment]
Here's what mine looks like

![image](https://cloud.githubusercontent.com/assets/10224994/22152787/7023c33a-def2-11e6-9d9f-6f5c38753db6.png)

**Comment by ItsHarper** [comment]
Once you post a screenshot of that page, go ahead and click "Update Driver", then "Browse my computer for driver software", then "Browse", then navigate to `C:\Program Files (x86)\QMK Firmware Flasher` and select that folder. If you don't have a Program Files (x86) folder, then it's in the regular Program Files Folder. Make sure "Include subfolders" is checked, and click next. I suspect that may solve your issue, but I still want to see what your driver tab shows.

**Comment by backstabbd88** [comment]
FIXED! 
It seems that windows has installed 2 versions of the driver, but it automatically installs the version from tmk
since its newer. everytime i uninstall the driver, it still reinstalls the newer version. So i thought that the one i installed was from qmk.

![driver fix](https://cloud.githubusercontent.com/assets/24477221/22157832/580dd2fe-df74-11e6-803f-2d2cca6a6f35.png)

thank you for pointing that out 

Heres what i did, after choosing Update driver> Browse for software on your computer>
i chose "Let me pick from a list", then it showed that i have 2 versions of the driver, Atm32U4DFU(from tmk) and Atmega32uf4(from qmk). 

Chose the 2nd option and it fixed it.

@skullydazed @NoahAndrews  thank you...

**Comment by ItsHarper** [comment]
Glad to hear it fixed it :)

Both screenshots on the left are of the "ATmega32U4" driver. Can you show me the one for the other driver?

**Comment by backstabbd88** [comment]
![atmega32u4 driver tkg](https://cloud.githubusercontent.com/assets/24477221/22171634/e2926d4c-dfcc-11e6-9d55-12b8106d8308.png)

i think part of the problem was windows 10 stores the drivers in the system even after uninstalling and checking the delete options.
![delete drivers](https://cloud.githubusercontent.com/assets/24477221/22171647/5eb635c0-dfcd-11e6-8f63-58405b6713b0.png)

And after that, windows automatically chooses the drivers and installs them when i put the keyboard on bootloader mode even after i disabled automatic driver installation in windows settings. When i try to manually install the drivers from qmk program folder, it will say that the driver is already updated.
