### ISSUE TITLE
New Windows 0.5.1 GUI Not Working

### ISSUE THREAD

**Issue by MagFlux** [qmk/qmk_flasher#45]
First off I just want to say, thanks for putting this utility together, it's very much appreciated.

As can be seen in the picture linked below, the GUI's layout seems to be all over the place with overlapping controls. Along with that, none of the buttons are actually pressable except for the 'X' button in the upper left corner.

For whatever it's worth, the older 0.5.0 version works perfectly for me and yes I made sure it was uninstalled before installing 0.5.1.

[Picture Of Issue](http://imgur.com/a/Ec82W)

Thanks again.

**Comment by skullydazed** [comment]
That's weird, looks like one of the CSS files didn't get loaded. Which version of windows are you on?

**Comment by MagFlux** [comment]
Windows 10 Pro (Ver. 1703)

Also for whatever it's worth I did try an uninstall and reinstall of 0.5.1 with no luck.

Thanks.

**Comment by skullydazed** [comment]
Weird, it's working fine on Window 7 but I just setup a Win 10 VM and it is broken there. I'll have to dig into this.

**Comment by MagFlux** [comment]
Huh, that is weird. Thanks again for looking into this, it's much appreciated!

**Comment by skullydazed** [comment]
Give this release a try: https://github.com/qmk/qmk_firmware_flasher/releases/tag/0.5.2

**Comment by MagFlux** [comment]
Works like a charm, thanks so much for the help and quickly resolving it!
