### ISSUE TITLE
Create Release for v1.00

### ISSUE THREAD

**Issue by robotmaxtron** [qmk/qmk_flasher#7]
There should be a release and subsequent installer for the newest version v1.0

**Comment by skullydazed** [comment]
We're a ways from v1.0. I think the next release will be 0.5.1 with @NoahAndrews's contributions, and followed by 0.6.0 with the basic/advanced GUI. We haven't decided what will make the 1.0 release, but I think the wix work and advanced mode features like #3 and #5 will be included.
